include: ['_pages', '_css', '_scripts', '_images']

title: Battle Spot Damage Calculator

github: [metadata]
  
url: "https://cantsay.github.io"
  
repository: cantsay/cantsay.github.io

description:
  Pokemon Damage Calculator for Gen 5, 6, 7, and 8 BSS and competitive LGPE, preloaded with viable sets for all formats.

